title: Se Explica Solamente Con El Corazón
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2759857
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#fffdff'
    - '#17418b'
    - '#6b80a1'
    - '#8ea2c7'
    - '#bfcbda'
  rhythmicContrast: 0.2885305
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Pasión Fortinera
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5681003
layout_spectrum: 0
