name: Pasión Fortinera
favicon: null
layout_spectrum: 0.9817433159332722
typography_spectrum: 0.9390571329277009
title: Se Explica Solamente Con El Corazón
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4569176349323243
  lightness: 0.3308623905759305
  saturation: 0.46521379239857197
  rhythmicContrast: 0.8266157479956746
purpose: []
