name: Pasión Fortinera
favicon: null
layout_spectrum: 0
typography_spectrum: 0.9390571329277009
title: Se Explica Solamente Con El Corazón
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffdff'
    - '#17418b'
    - '#6b80a1'
    - '#8ea2c7'
    - '#bfcbda'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.46521379239857197
  rhythmicContrast: 0.75
purpose: []
